#!/usr/bin/python
import os.path
import sys
import struct

BASE_DIR_64 = "/usr/lib64/ks-ssr/timeshift"
BASE_DIR_32 = "/usr/lib/ks-ssr/timeshift"

if struct.calcsize("P") * 8 == 64:
    BASE_DIR = BASE_DIR_64
else:
    if os.path.exists(BASE_DIR_64):
        BASE_DIR = BASE_DIR_64
    else:
        BASE_DIR = BASE_DIR_32

sys.path.insert(0, BASE_DIR)

try:
    import timeshift_main
    timeshift_main.main()
except KeyboardInterrupt:
    print >> sys.stderr, "\n\nExiting on user cancel."
    sys.exit(1)
