#!/bin/bash
#
# Init file for ks-ssr-daemon BINARY_FILE
#
# chkconfig: 2345 99 95
# description: ks-ssr-daemon BINARY_FILE
#
# source function library
# . /etc/rc.d/init.d/functions

PRIFIX=/usr
BINARY_FILE_PATH="$PRIFIX/bin/"
BINARY_FILE=ks-ssr-daemon

PIDFILE=/var/run/$BINARY_FILE.pid
SCRIPTNAME=/etc/rc.d/init.d/$BINARY_FILE
source /etc/sysconfig/i18n
export LANG

case "$1" in
start)
    printf "%-50s" "Starting $BINARY_FILE..."
    cd $BINARY_FILE_PATH
    PID=`$BINARY_FILE  > /dev/null 2>&1 & echo $!`
    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi
;;
status)
        printf "%-50s" "Checking $BINARY_FILE..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps -ef | grep $PID | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $BINARY_FILE"
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac