/**
 * Copyright (c) 2023 ~ 2024 KylinSec Co., Ltd.
 * ks-ssr is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 * Author:     chendingjian <chendingjian@kylinsec.com.cn>
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

    enum SSRErrorCode
    {
        // Common
        SUCCESS,
        ERROR_FAILED,
        ERROR_COMMON_INVALID_ARGS,

        // Main
        ERROR_PLUGIN_NOT_EXIST_1 = 0x0100,
        // ERROR_SET_STANDARD_TYPE_FAILED,

        // core
        ERROR_CUSTOM_RS_DECRYPT_FAILED,
        ERROR_CORE_REINFORCE_JOB_FAILED,

        // plugins
        // plugin br
        ERROR_PLUGIN_BR_STANDARD_TYPE_INVALID = 0x0200,
        ERROR_PLUGIN_BR_SET_STANDARD_TYPE_FAILED,
        ERROR_PLUGIN_BR_STRATEGY_TYPE_INVALID,
        ERROR_PLUGIN_BR_SET_STRATEGY_TYPE_FAILED,
        ERROR_PLUGIN_BR_SET_TIME_SCAN_FAILED,
        ERROR_PLUGIN_BR_NOTIFICATION_STATUS_INVALID,
        ERROR_PLUGIN_BR_SET_NOTIFICATION_STATUS_FAILED,
        ERROR_PLUGIN_BR_RESOURCE_MONITOR_INVALID,
        ERROR_PLUGIN_BR_SET_RESOURCE_MONITOR_FAILED,
        ERROR_PLUGIN_BR_SET_REINFORCEMENT_FAILED,
        ERROR_PLUGIN_BR_REINFORCEMENT_NOTFOUND,
        ERROR_PLUGIN_BR_GEN_REINFORCEMENT_FAILED,
        ERROR_PLUGIN_BR_JOB_IS_RUNNING,
        ERROR_PLUGIN_BR_NEED_CUSTOM_STRATEGY_TYPE,

        // plugin audit
        ERROR_PLUGIN_AUDIT_GET_JSON_ERROR = 0x0300,
        ERROR_PLUGIN_AUDIT_SET_JSON_ERROR,

        // plugin config
        ERROR_PLUGIN_CONFIG_REINFORCEMENT_NOTFOUND = 0x0400,
        ERROR_PLUGIN_CONFIG_UNSUPPORTED_REQ,
        ERROR_PLUGIN_CONFIG_JSON_EXCEPTION,

        // KSS, FP and TP Trusted protect
        ERROR_TP_ADD_INVALID_FILE = 0x0500,
        ERROR_TP_ADD_RECUR_FILE,
        ERROR_CHANGE_STORAGE_MODE_FAILED,
        ERROR_USER_PIN_ERROR,

        // BM PrivateBox manager
        ERROR_BM_DELETE_FAILED = 0x0600,
        ERROR_BM_MOUDLE_UNLOAD,
        ERROR_BM_MKDIR_DATA_DIR_FAILED,
        ERROR_BM_NOT_FOUND,
        ERROR_BM_REPEATED_NAME,
        ERROR_BM_SETTINGS_SAME_PASSWORD,
        ERROR_BM_UMOUNT_FAIL,
        ERROR_BM_MODIFY_PASSWORD_FAILED,
        ERROR_BM_CHECK_PASSWORD_FAILED,
        ERROR_BM_INPUT_PASSWORD_ERROR,
        ERROR_BM_INPUT_PASSPHRASE_ERROR,
        ERROR_BM_INTERNAL_ERRORS,

        // Device manager
        ERROR_DEVICE_INVALID_ID = 0x0700,
        ERROR_DEVICE_INVALID_PERM,
        ERROR_DEVICE_INVALID_IFC_TYPE,
        ERROR_DEVICE_DISABLE_HDMI,

        // Account
        ERROR_ACCOUNT_PASSWORD_ERROR = 0x0800,
        ERROR_ACCOUNT_BE_FREEZE,
        ERROR_ACCOUNT_BE_DIFF_NEW_PASSWORD,
        ERROR_ACCOUNT_CHECK_PASSWORD_FAILED,
        ERROR_ACCOUNT_PERMISSION_DENIED,
        ERROR_ACCOUNT_UNKNOWN_ACCOUNT,
        ERROR_ACCOUNT_FAILED_SET_MULTI_FACTOR_AUTH_STATE,

        // Log
        ERROR_LOG_GET_LOG_PAGE_ERROR = 0x0900,

        // Tool Box
        ERROR_TOOL_BOX_FAILED_SET_ACCESS_CONTROL = 0x0a00,
        ERROR_TOOL_BOX_FAILED_SET_MLS_CONTEXT,
        ERROR_TOOL_BOX_FAILED_SET_KIC_CONTEXT,
        ERROR_TOOL_BOX_FAILED_GET_MLS_CONTEXT,
        ERROR_TOOL_BOX_FAILED_GET_KIC_CONTEXT,
        ERROR_TOOL_BOX_FAILED_ADD_OBJ_TO_SECURITY_SIGN,
        ERROR_TOOL_BOX_FAILED_REMOVE_USERS,
        ERROR_TOOL_BOX_FAILED_SHRED_FILES,

        // Vulnerability
        ERROR_VULNERABILITY_TASK_RUNNING = 0x0b00
    };
#ifdef __cplusplus
}
#endif
