include(GNUInstallDirs)

set(SC_INSTALL_DATADIR ${CMAKE_INSTALL_FULL_DATADIR}/${PROJECT_NAME})
set(SC_INSTALL_INCLUDE ${CMAKE_INSTALL_FULL_INCLUDEDIR}/${PROJECT_NAME})
set(SC_INSTALL_TRANSLATIONDIR ${SC_INSTALL_DATADIR}/translations)
set(GETTEXT_PACKAGE ${PROJECT_NAME})

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED on)
