include(GNUInstallDirs)

set(KSC_INSTALL_DATADIR ${CMAKE_INSTALL_FULL_DATADIR}/${PROJECT_NAME})
set(SC_INSTALL_INCLUDE ${CMAKE_INSTALL_FULL_INCLUDEDIR}/${PROJECT_NAME})
set(KSC_INSTALL_SYSCONFDIR ${CMAKE_INSTALL_FULL_SYSCONFDIR}/${PROJECT_NAME})
set(KSC_INSTALL_TRANSLATIONDIR ${KSC_INSTALL_DATADIR}/translations)
set(GETTEXT_PACKAGE ${PROJECT_NAME})

set(KSC_BOX_MOUNT_DIR /box)
set(KSC_BOX_MOUNT_DATADIR ${KSC_INSTALL_DATADIR}/box)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED on)

option(USE_SYSTEMD "Use systemd or upstart" ON)
